### ISSUE TITLE
where did you find this repo? 🤣

### ISSUE THREAD

**Issue by sacconazzo** [amnariaz007/BNB-Dapp#1]

**Comment by amnariaz007** [comment]
I think so I cloned this from my friend's repo two years ago 😂. What’s the matter mate ?

**Comment by sacconazzo** [comment]
> I think so I cloned this from my friend's repo two years ago 😂. What’s the matter mate ?

Maybe your friend is my account.
I recognize this code well 🤣🤣

**Comment by amnariaz007** [comment]
Well, I don’t have to lie to you because I don’t even know you, what I have cloned from other's profiles I know it's from my friends as far as I remember and never used it other than showcasing on my GitHub

**Comment by sacconazzo** [comment]
this is the original project: 

https://github.com/sacconazzo/defi-simple-dapp

That's it!

You can also tell your friends, you can see the creation date.

**I wrote the project myself from scratch** and yours is identical to mine.

Finally, I'm glad it was useful to someone.

Good luck. :)
Giona

**Comment by amnariaz007** [comment]
I see you updated this year ago as well but the one I have on my GitHub is old. 
and yes my friend may have used this because he’s a real stalker and a freelancer too. 

btw how did you come across my profile, I'm just curious about how someone messaged me about his repo which was clonned years ago.

**Comment by sacconazzo** [comment]
I don't know you either, but I know the code well and knew what to look for.
Even if it was only a demo, I had dedicated effort and several hours to it :) ..

**Comment by amnariaz007** [comment]
> I don't know you either, but I know the code well and know what to look for. Even if it was only a demo, I had dedicated effort and several hours to it :).

Alright, but it was not the answer to my question anyhow I found this repo on my friend's github.
P.S. If you commit anything to GitHub publically this means you don’t care who clones it or not next time take care of that and add the security that no one can upload it with his name on your code they can just fork your repo if you're too concerned about your code.

**Comment by sacconazzo** [comment]
A thank you or a fork is certainly more appreciated, but in any case the code is public.
I just think that if someone publishes a portfolio he should at least be the author.

I haven't found any other cloned repos on github other than yours and some forks on yours.

**Comment by amnariaz007** [comment]
> A thank you or a fork is certainly more appreciated, but in any case the code is public. I just think that if someone publishes a portfolio he should at least be the author.
> 
> I haven't found any other cloned repos on github other than yours and some forks on yours.

bro, I think so you gotta a problem believing me just because I kept this repo public doesn’t mean everyone else would also do this, I have checked my friend's GitHub now and he has changed every repo to Private. But I'll ask him to send me a screenshot of your code in his repo.
It has no use in my GitHub do you want me to delete it? because you keep pushing this thing.

**Comment by sacconazzo** [comment]
> A thank you or a fork is certainly more appreciated, but in any case the code is public.
> I just think that if someone publishes a portfolio he should at least be the author.

There are no problems and I It's just a small demo.

**Comment by amnariaz007** [comment]
Would you please mind giving me your LinkedIn username or profile link. I think we should get connect there.

**Comment by sacconazzo** [comment]
You can find with the same nickname or full name. :) thanks
